version: '3.9'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: solace-searxng-official
    ports:
      - "8088:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
