# This is the configuration file for SearXNG.
# See https://docs.searxng.org/admin/settings.html for more information.

server:
  # You must change this to a long random string.
  # You can generate one with `openssl rand -hex 32`
  secret_key: "a5d9b3c7e1f3a9b8c7d5e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2"
  
  # The base_url is the URL where SearXNG is hosted.
  # It MUST match the external URL.
  base_url: http://localhost:8088/

# By default, SearXNG uses the settings from its internal default settings file.
# If you want to override a setting, you can uncomment it and change the value.
use_default_settings: true

search:
  # Enable the JSON format which is needed for our application to parse the results.
  formats:
    - html
    - json
    - csv
    - rss

# Security settings
security:
  # This is important for allowing our local server to fetch results.
  # It's generally safe in a trusted local environment.
  x_content_type_options: ""
